acc/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name = "logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete', views.delete, name="delete"),
    path('mod/', views.usermod, name="mod"),
    
]

book/urls.py
from unicodedata import name
from django.urls import path
from . import views
app_name = 'book'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('pdf/', include("pdfread.urls")),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from unicodedata import name
from django.urls import path
from . import views
app_name = "vote"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail<vpk>', views.detail, name="detail"),
    path('vote/<vpk>', views.vote, name="vote"),
    path('cancel<vpk>', views.cancel, name="cancel"),
    path('create/', views.create, name="create"),
    path('del/<vpk>', views.del_u , name="del")
]

vote/models.py
from distutils.command.upload import upload
from django.db import models
from acc.models import User
# Create your models here.
class Topic(models.Model):
    subject = models.TextField()
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        return f"{self.content[0:15]}..."

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    chname = models.CharField(max_length=100)
    chpic = models.ImageField(upload_to="vote/%y")
    chcom = models.TextField()

    choicer = models.ManyToManyField(User,blank=True)

    def __str__(self):
        return f"{self.topic}_{self.chname}"

    def getpic(self):
        if self.chpic:
            return self.chpic.url
        return "/media/noimg.png"
        

vote/views.py
from django.shortcuts import redirect, render
from .models import Topic,Choice
# Create your views here.
def index(request):
    t = Topic.objects.all()
    t = t.order_by("-pubdate")
    context={
        "tset":t
    }
    return render(request,"vote/index.html",context)

def detail(request,vpk):
    t = Topic.objects.get(id=vpk)
    cho = t.choice_set.all()
    context = {
        't':t,
        "cset":cho
    }
    return render(request,'vote/detail.html',context)

def del_u(request,vpk):
    t = Topic.objects.get(id = vpk)
    if request.user == t.maker:
        t.delete()
    return redirect('vote:index')

def vote(request,vpk):
    t = Topic.objects.get(id = vpk)
    if not request.user in t.voter.all(): #투표자에 유저가 없다면 추가하고 있으면 추가안함
        t.voter.add(request.user)

        cpk = request.POST.get("ch")
        c = Choice.objects.get(id = cpk)
        c.choicer.add(request.user)

    return redirect('vote:detail',vpk)

def cancel(request,vpk):
    t = Topic.objects.get(id= vpk)
    u = request.user
    if u in t.voter.all():
        t.voter.remove(u)
        u.choice_set.get(topic = t).choicer.remove(u) 
        #유저가 고른것중에 가져와라 topic이 t인것을 , u가 투표한 초이스 레코드
    return redirect('vote:detail',vpk)

from django.utils import timezone
def create(request):
    if request.method =="POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        
        names = request.POST.getlist("chname")       
        files = request.FILES.getlist("pic")
        cons = request.POST.getlist("chcon")
        
        t = Topic(subject = s, maker = request.user, content = c, pubdate=timezone.now())
        t.save()
        if len(names)>1:
            for i,j,k in zip(names, files, cons):
                c = Choice(topic = t, chname = i, chpic = j, chcom = k)
                print(c)
                c.save()
            return redirect('vote:index')
        else:
            return redirect('vote:create')

    return render(request, 'vote/create.html')

templates/vote/create.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <h1><b>Topic 작성</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" class="form-control" name="sub">
            </div>
            <div class="mb-3">
                <label class="form-label">Maker</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" style="height: 100px;" name="con"></textarea>
            </div>

            <div class="text-center">
                <button type="button" onclick="make()" class="btn btn-dark">보기 생성</button>
            </div>
            <div class="row" id="here">
                
            </div>   

            <div class="text-end mt-3">
                <button class="btn btn-success">생성</button>
            </div>
        </form>
    </div>

<script>
    function make(){
        d = document.getElementById("here")
        n = document.createElement("div")
        n.setAttribute('class', 'col-lg-4 mt-2')
        n.innerHTML ='<input type="text" name="chname" class="form-control mt-5" placeholder="입력하세요">\
                    <input type="file" name="pic" class="form-control mt-2 mb-2">\
                    <textarea class="form-control" name="chcon" placeholder="설명해주세요"></textarea>'
        d.appendChild(n)
    }
</script>
{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block con %}
<div class="container mt-5 mb-5">
        <h1>Vote Page👀</h1>
        
        <hr>
    <div class="text-end">
        <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal2">
            POST💖
        </button>
    </div>
    <hr>
    <div class="row mt-5">
        <div class="col-lg-8"><textarea class="form-control" style="height: 300px;" disabled>{{ t.content }}</textarea></div>
        <div class="col-lg-4" style="margin:auto">
            <img src="{{ t.maker.getpic }}" width="100%">
            <div class="text-center">
                made by <b>{{ t.maker }}</b>
                <br>{{ t.pubdate | date:'y.m.d  H:i' }}
            </div>
        </div>
    </div>
    <hr>
    {% if user in t.voter.all %}
        <div class="row mt-2">
            {% for i in cset %}
                <div class="col-lg-4">
                    
                    <div class="mt-2 mb-2 text-center">
                        {{ i.chname }}
                    </div>
                    <img src="{{ i.getpic }}" width="100%">
                    <div class="progress mt-2">
                        <div class="progress-bar" role="progressbar" style="width: {{ i.choicer.all.count | div:t.voter.all.count | mul:100 }}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                            {{ i.choicer.all.count | div:t.voter.all.count | mul:100 }}%</div>
                    </div>
                    
                </div>
            {% endfor %}
            <a href="{% url 'vote:cancel' t.id %}"><button class="btn btn-danger btn-lg">취소하기</button>  </a>
        </div>
    {% else %}
        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            <div class="row mt-2">
                {% for i in cset %}
                    <div class="col-lg-4">
                        
                        <div class="mt-2 mb-2 text-center">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="ch" value="{{ i.id }}" {% if forloop.first %}checked{% endif %}>
                            </div>
                            {{ i.chname }}
                        </div>
                        <img src="{{ i.getpic }}" width="100%">
                        <textarea class="form-control mt-2" disabled>{{ i.chcom }}</textarea>
                    </div>
                {% endfor %}
            </div>
            <div class="text-center mt-4">
                <button class="btn btn-dark btn-lg">투표하기</button>  
            </div>
        </form>
    {% endif %}
    {% if user == t.maker %}
        <div class="text-end">
            <a href="{% url 'vote:del' t.id %}"><button class="btn btn-danger">주제 삭제</button></a>
        </div>    
    {% endif %}
</div>








<!-- Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>

    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal-body">
        <!-- 밑에는 중요도 -->
        <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
            <input type="checkbox" name="info" class="btn-check" id="btncheck2" autocomplete="off">
            <label class="btn btn-outline-warning" for="btncheck2">★</label>
        </div>
        <input type="hidden" name="sname" value="[투표]{{ t.subject }}">
        <input type="hidden" name="surl" value="{{ request.path }}">
        <b>사이트 설명</b> <input type="text" name="scom" class="form-control mt-2">
        </div>
    

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-primary">Save Add</button>
    </div>
    </form> 
    </div>
</div>
</div>
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block con %}
<div class="container mt-5 mb-5">
        <h1>Vote Page👀</h1>
        <br><br>
    <div class="text-end">
        <a href="{% url 'vote:create' %}" class="btn btn-dark">Topic 생성</a>
    </div>
        
    <div class="row mt-5">
        {% for i in tset %}
            <div class="col-lg-4 mt-5">
                <div class="card" style="width: 18rem;">
                    <img src="{{ i.maker.getpic }}" class="card-img-top" alt="...">
                    <div class="card-body" {% if user in i.voter.all %} style="background-color: aqua;" {% endif %}>
                    <h4 class="card-title"><b>{{ i.subject }}</b></h4>
                    <p class="card-text">{{ i.summary }}</p>
                    <div class="text-end"><a href="{% url 'vote:detail' i.id %}" class="btn btn-primary">
                        {% if user in i.voter.all %}결과보기{% else %}투표하기{% endif %}</a></div>
                    </div>
                </div>
            </div>    
        {% endfor %}
    </div>
        

</div> 

{% endblock %}