acc/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name = "logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete', views.delete, name="delete"),
    path('mod/', views.usermod, name="mod"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('pdf/', include("pdfread.urls")),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    comment = models.TextField()
    point = models.IntegerField(default=0)
    age = models.IntegerField(default=0)
    pic = models.ImageField(upload_to="user/%y/%m")

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimg.png"

acc/views.py
from ast import UAdd
from turtle import up
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.
def index(request):
    return render(request, "acc/index.html")

def login_user(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        pw = request.POST.get("upass")
        user = authenticate(username=un, password=pw)
        if user:
            login(request, user)
            messages.success(request, f": {user}님 환영합니다! :)")
            return redirect("acc:index")
        else:
            messages.error(request,": LOGIN FAIL")
    return render(request, "acc/login.html")

def logout_user(request):
    logout(request)
    return redirect('acc:login')

from .models import User
def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ua = request.POST.get("uage")
        ut = request.POST.get("utext")
        upic = request.FILES.get("upic")
        
        try:          
            User.objects.create_user(username = un, password = up, comment = ut, age = ua, pic = upic)
        except:
            messages.error(request,f"{un} 이미 존재합니다.")
        return redirect("acc:login")
    return render(request,"acc/signup.html")

def profile(request):
    return render(request,'acc/profile.html')

from django.contrib.auth.hashers import check_password
def delete(request):
    ck = request.POST.get("ckpw")
    if check_password(ck, request.user.password):
        print("1222345")
        # request.user.pic.delete()
        # request.user.delete()
        return redirect('acc:index')
    else:
        pass #19일
    return redirect('acc:profile')


def usermod(request):
    if request.method =="POST":
        u = request.user
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("utext")
        ua = request.POST.get("uage")
        upic = request.FILES.get("upic")

        if up:
            u.set_password(up)

        if upic:
            request.user.pic.delete()
            u.pic = upic
        u.username = un
        u.comment = uc
        u.age = ua
        u.save()
        login(request,u)
        return redirect("acc:profile")

    return render(request,'acc/update.html')

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">김치찌개 좋아하시는 분 ~~ </h1>
            <p class="col-md-8 fs-4">된장찌개 좋아하시는 분 나가세요!</p>
            <img src="{{ user.getpic }}" width="50%">
        </div>
    </div>   
{% endblock %}


{% block noauth %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">김치찌개 좋아하시는 분 ~~ </h1>
            <p class="col-md-8 fs-4">된장찌개 좋아하시는 분 나가세요!</p>
            <a href="{% url 'acc:login' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">LOGIN</button></a>
        </div>
    </div>  
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block noauth %}
    
    <div class="container mt-5 mb-5" style="width: 60%;">
        <h1><b>로그인</b></h1>

        <form method="post">
            {% csrf_token %}
            <div class="mt-5">
                <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
                <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
            </div>
            <div class="text-end mt-4">
                <button class="btn btn-dark">LOGIN</button>
            </div>
        </form>
        
    </div>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 60%;">
        <h1><b>프로필</b></h1>

        <div class="text-center mt-5">
            <img src="{{ user.getpic }}" class="rounded-circle" width="250px    ">
        </div>

        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{ user.username }}" disabled class="form-control" style="font-weight: bold;" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">AGE</label>
            <input type="text" style="font-weight: bold;" value="{{ user.age }}" disabled class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">POINT</label>
            <input type="text" style="font-weight: bold;" value="{{ user.point }}P" disabled class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{ user.comment }}</textarea>
        </div>

        <div class="text-end">
            <a href="{% url 'acc:mod' %}" class="btn btn-dark">정보수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                계정삭제
            </button>
        </div>
    </div>


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>계정 삭제 알림</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:delete' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <h5>정말로 삭제하시겠습니까?</h5>
                        <b>패스워드 확인</b> <input type="password" name="ckpw" class="form-control mt-2">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button class="btn btn-danger" style="font-weight: bold; font-family:monospace;">계정삭제</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block noauth %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="container mt-5 mb-5" style="width: 60%; font-weight: bold; font-size: 20px;">
                    <h1><b>회원가입</b></h1>
                    <div class="mb-3 mt-5">
                        <label for="exampleInputEmail1" class="form-label">USERNAME</label>
                        <input type="text" name="uname" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
                        <input type="password" name="upass" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">AGE</label>
                        <input type="number" name="uage" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">COMMENT</label>
                        <textarea class="form-control" name="utext"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">USERPIC</label>
                        <input type="file" class="form-control" name="upic" id="exampleInputPassword1">
                    </div>
                    <div class="mt-4 text-end">
                        <button type="submit" class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}

{% block con %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container mt-5 mb-5"  style="font-size: 20px; font-weight: bold; width: 60%;">
        <h1><b>정보수정</b></h1>
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{ user.username }}" name="uname" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">PASSWORD</label>
            <input type="password" class="form-control" name="upass" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
            <label class="form-label">AGE</label>
            <input type="number" class="form-control" name="uage" value="{{ user.age }}" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" name="utext">{{ user.comment }}</textarea>
        </div>
        <div class="mb-3">
            <label class="form-label">USERPIC</label>
            <input type="file" class="form-control" id="exampleInputEmail1" name="upic" aria-describedby="emailHelp">
        </div>
        <div class="text-end">
            <a href="{% url 'acc:profile' %}"><button type="button" class="btn btn-dark">BACK</button></a>
            <button class="btn btn-dark">UPDATE</button>
        </div>
    </div>
</form>
{% endblock %}