acc/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name = "logout"),
    path('signup/', views.signup, name="signup"),
    path('profile/', views.profile, name="profile"),
    path('delete', views.delete, name="delete"),
    path('mod/', views.usermod, name="mod"),
    
]

board/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
   path("index/", views.index, name="index"),
   path('detail/<bpk>', views.detail, name="detail"),
   path('delete/<bpk>',views.delete_con, name="delete"),
   path('create/', views.create, name="create"),
   path('update/<bpk>', views.update, name="update"),
   path('creply/<bpk>', views.creply, name="creply"),
   path('board:delete_reply/<ipk><bpk>', views.delete_reply, name="delete_reply"),
   path('trans/', views.trans, name="TRANS"),
   path('likey/<bpk>', views.likey, name="likey"),
   path('bad/<bpk>', views.bad, name="bad"),
]

book/urls.py
from unicodedata import name
from django.urls import path
from . import views
app_name = 'book'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('pdf/', include("pdfread.urls")),
    path('vote/', include('vote.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from tkinter import CASCADE
from django.db import models
from acc.models import User
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True ,related_name="likey")
    pubdatd = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 60:
            return f"{self.content[:60]} ..."
        return f"{self.content}"

class Reply(models.Model):
    b = models.ForeignKey(Board,on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.b}_{self.replyer}"

board/views.py
from multiprocessing import context
from django.shortcuts import redirect, render
import googletrans
from .models import Board, Reply
# Create your views here.
from django.core.paginator import Paginator
from django.contrib import messages

def index(request):
    pg = request.GET.get('page',1)
    cate = request.GET.get("cate","")
    kw = request.GET.get("kw","")

    if kw:#키워드가있을때
        if cate == "sub":
            b = Board.objects.filter(subject__contains=kw)
        elif cate == "wri":
            from acc.models import User
            try:
                u = User.objects.get(username = kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.all()
    else:
        b = Board.objects.all()

    b = b.order_by("-pubdatd")
    pag = Paginator(b, 10)
    obj = pag.get_page(pg)
    context = {
        "bset" : obj,
        "cate" : cate,
        "kw" : kw
    }
    return render(request,"board/index.html",context)

from googletrans import Translator


def trans(request):
    context = {"ndict": googletrans.LANGUAGES}

    if request.method == "POST":
        text = request.POST.get("bf")
        fr = request.POST.get("fr")
        to = request.POST.get("to")
        translator = Translator()
        
        if text:
            inter = translator.translate(text, src=fr , dest=to)
        
            context.update({
                'af':inter.text,
                'text' : text,
                'fr' : fr,
                'to' : to,
            })
        
    return render(request, 'board/trans.html',context)

def detail(request,bpk):
    a = Board.objects.get(id = bpk)
    r = a.reply_set.all()
    context = {
        'a' : a,
        "rset":r
    }
    return render(request,"board/detail.html", context)

def creply(request,bpk):
    c = request.POST.get("com")
    b = Board.objects.get(id=bpk)
    Reply(b = b, replyer = request.user, comment = c, pubdate = timezone.now()).save()
    return redirect("board:detail",bpk)

def delete_con(request,bpk):
    a = Board.objects.get(id = bpk)
    if request.user == a.writer:
        a.delete()
    else:
        messages.info(request,"삭제할수없는 글입니다")
    return redirect("board:index")

def delete_reply(request,bpk,ipk):
    a = Reply.objects.get(id = ipk)
    if request.user == a.replyer:
        a.delete()
        messages.info(request,"삭제했습니다.")
    # else:
    #     pass#안내메세지 
    return redirect("board:index")

from django.utils import timezone
def create(request):
    if request.method == "POST":
        # print(request.POST)
        s = request.POST.get("bsub")
        c = request.POST.get("bcon")
        if s and c:
            Board(subject = s, content = c, writer=request.user, pubdatd=timezone.now()).save()
        # try:          
        #     Board(subject = s, content = c,pubdate=timezone()).save()
        # except:
        #     pass
        return redirect("board:index")
    return render(request,"board/create.html")

def update(request,bpk):   
    b = Board.objects.get(id = bpk)
    context = {
        'b':b
    }
    if request.user == b.writer:
        #19일차 메세지
        return redirect("board:index")

    if request.method == "POST":    
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect('board:detail',bpk)
    return render(request,'board/update.html',context)

def likey(request,bpk):
    b = Board.objects.get(id = bpk)
    b.likey.add(request.user)
    return redirect("board:detail",bpk)

def bad(request,bpk):
    b = Board.objects.get(id = bpk)
    b.likey.remove(request.user)
    return redirect('board:detail',bpk)

templates/board/create.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
        <h1><b>게시글 작성</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" class="form-control" name="bsub">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" style="height: 100px;" name="bcon"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ a.subject }}</b></h1>
        <br>
        <div class="row">
            <div class="col-lg-8">
               <textarea class="form-control" style="height: 300px;" disabled>{{ a.content }}</textarea>
            </div>
            <div class="col-lg-4" style="margin:auto">
                <img src="{{ a.writer.getpic }}" width="100%">
                <div class="mt-5 text-center">
                    written by <b>{{ a.writer }}</b>
                </div>
                <div class="mt-2 text-center">
                    {{ a.pubdatd | date:'y.m.d  H:i' }}
                </div>
            </div>
        </div>

        <div class="text-end mt-5">
            <a href="{% url 'board:index' %}" class="btn btn-dark btn-lg">BACK</a>
            {% if a.writer == user %}
                <a href="{% url 'board:update' a.id %}"><button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                MOD</button></a>
                <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                DEL</button>
            {% endif %}        
        </div>

        <div class="text-end mt-2 mb-2">
            {% if user in a.likey.all %}
              <a href="{% url 'board:bad' a.id %}" class="btn btn-danger btn-lg">Bad👎</a>
              <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal2">
                POST💖
              </button>        
            {% else %}
              <a href="{% url 'board:likey' a.id %}" class="btn btn-primary btn-lg">Likey👍</a>
              <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal2">
                POST💖
              </button>
            {% endif %}    
                   
            
        </div>
        
        <hr>
        <form method="post" action="{% url 'board:creply' a.id %}">
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-10">
              <input type="text" name="com" class="form-control" placeholder="댓글을 남겨주세요">    
            </div>
            <div class="col-lg-2">
              <button class="btn btn-dark">확인</button>
            </div>
          </div>
        </form> 

        <div class="container mt-2" style="width: 100%;">
          {% if rset %}
            {% for i in rset %}
              <div class="row">
                <div class="col-lg-3 text-center">
                  <img src="{{ i.replyer.getpic }}" width="100%">
                  <div>
                    <b>{{ i.replyer }}</b>
                  </div>
                </div>
                <div class="col-lg-9" style="margin: auto;">
                  <textarea class="form-control" disabled>{{ i.comment }}</textarea>
                  <div class="text-end mt-3">
                    {% if a.writer == user %}
                      <a href="{% url 'board:delete_reply' i.id a.id %}"><button class="btn btn-danger btn-sm">댓글삭제</button></a>
                    {% else %}
                      <a href="{% url 'board:index' %}"><button class="btn btn-success btn-sm">추천</button></a>
                    {% endif %}  
                  </div>
                </div>

                
              </div>
            {% endfor %}
          {% else %}
            <h3>첫번째 댓글을 달아주세요</h3>
          {% endif %}
        </div>
    </div>



    <!--modal창-->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">게시글 삭제 알림
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              정말 삭제 하시겠습니까?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
              <a href="{% url 'board:delete' a.id %}"><button type="button" class="btn btn-danger">삭제</button></a>
            </div>
          </div>
        </div>
      </div>

      <!-- Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal-body">
          <!-- 밑에는 중요도 -->
          <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
            <input type="checkbox" name="info" class="btn-check" id="btncheck2" autocomplete="off">
            <label class="btn btn-outline-warning" for="btncheck2">★</label>
          </div>
          <input type="hidden" name="sname" value="[게시판]{{ a.subject }}">
          <input type="hidden" name="surl" value="{{ request.path }}">
          <b>사이트 설명</b> <input type="text" name="scom" class="form-control mt-2">
        </div>
      

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button class="btn btn-primary">Save Add</button>
      </div>
    </form> 
    </div>
  </div>
</div>
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block con %}
    
    <div class="container mt-5" style="width:100%">
        <h1><b>웹서버 갤러리</b></h1>
        <table class="table table-striped table-hover mt-4">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Summary</th>
                    <th scope="col">Writer</th>
                    <th scope="col">Likey</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a class="sub" href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer }}</td>
                            <td>{{ i.likey.all.count }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr>
                            <td colspan="5">검색결과가 없습니다</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">게시글을 작성해주세요</td>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>
        
        <div class="row mt-5">
            <div class="col-lg-10 text-center">
                <form>
                    <select name="cate">
                        <option value="sub" {% if cate == "sub" %}selected{% endif %}>제목</option>
                        <option value="wri" {% if cate == "wri" %}selected{% endif %}>글쓴이</option>
                        <option value="con" {% if cate == "con" %}selected{% endif %}>내용</option>
                        <input name="kw" type="text" size="50" value="{{kw}}"><button>검색</button>
                    </select> 
                </form>
            </div>
            <div class="col-lg-2 text-end">
                <a href="{% url 'board:create' %}"><button type="button" class="btn btn-success btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    글쓰기</button></a>
            </div>    
       </div>
       
    <div class="row">
        <div class="col-lg-11">
            <nav aria-label="Page navigation example">
                <ul class="pagination nav justify-content-center">
                   
                    {% if bset.has_previous %}
                        <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{1}}&cate={{cate}}&kw={{kw}}">Home</a></li>
                        <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}">Previous</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link disabled">Home</a></li>
                        <li class="page-item"><a class="page-link disabled">Previous</a></li>
                    {% endif %}    
                    {% for i in bset.paginator.page_range %}
                        {% if i >= bset.number|sub:5 and i <= bset.number|add:4 %}
                            <li class="page-item  {% if i == bset.number %}active{% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                        {% endif %}
                    {% endfor %}
        
                    {% if chset.has_next %}
                        <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}">Next</a></li>
                        <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}">End</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link disabled">Next</a></li>
                        <li class="page-item"><a class="page-link disabled">End</a></li>    
                    {% endif %}    
                </ul>
            </nav>
        </div>
        <div class="col-lg-1"></div>
    </div>   
    
   
{% endblock %}

templates/board/trans.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block con %}

<div class="container mt-5 row" style="width:100%">
    <h1><b>번역기</b></h1>
    <table class="table table-striped table-hover mt-4">
        <thead>
            <tr>
               
            </tr>
        </thead>
        
    </table>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-5">
                <textarea class="form-control" rows="10" cols="40" name="bf" 
                placeholder="입력해주세요">{{text}}</textarea>
            </div>

            <div class="col-lg-2 text-center" style="margin: auto;">
                <select name="fr" class="form-select" size="7" aria-label="size 7 select example">
                    {% for code, name in ndict.items %}
                        <option value="{{ code }}" {% if fr %}{% if fr == code %} selected {% endif %}{% else %}
                        {% if code == 'ko'%}selected{% endif %}{% endif %}>{{ name | upper }}</option>
                    {% endfor %}
                </select>

                <button class="btn btn-outline-dark mt-3 mb-3">번역</button>

                <select name="to" class="form-select" size="7" aria-label="size 7 select example">
                    {% for code, name in ndict.items %}
                        <option value="{{ code }}" {% if to %}{% if to == code %} selected {% endif %}{% else %}
                        {% if code == 'en' %}selected{% endif %}{% endif %}>{{ name | upper }}</option>
                    {% endfor %} 
                </select>
            </div>

            <div class="col-lg-5">
                <textarea class="form-control"  rows="10" cols="40" disabled>{{af}}</textarea>
            </div>
        </div>
    </form>
    
</div>
   
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}

{% block con %}
    <form method="post">
        {% csrf_token %}
        <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold; width: 80%;">
            <h1><b>게시글수정</b></h1>
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" class="form-control" value="{{ b.writer }}" name="sub">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" disabled value="{{ user }}">
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" style="height: 100px;" name="con">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정하기</button>
            </div> 
        </div>
    </form>
{% endblock %}